version: '3.8'

services:
  # Backend .NET API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: facial-recognition-backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080    

  # Frontend React Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: facial-recognition-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend   
